# Generated by Django 5.2.7 on 2026-04-01 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_limit', models.PositiveIntegerField(help_text='Time limit in minutes')),
                ('total_questions', models.PositiveIntegerField(help_text='Number of questions shown per exam attempt')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='subjects.subject')),
            ],
            options={
                'ordering': ['subject', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
    ]
